// The delta download protocol has the server (librsync-go) produce a signature
// that this client (fast_rsync) consumes. Nothing else exercises that pairing:
// upload goes the other way and signatures never cross the wire there. The
// fixture was generated by the filestash server implementation over 1MiB of
// deterministic data:
//
//   librsync.Signature(data, out, 4096, 16, librsync.MD4_SIG_MAGIC)
//
// where data is the LCG below. fast_rsync rejects anything but MD4 with a
// strong hash of at most 16 bytes, so this test failing means the server
// signature parameters drifted out of what the client can consume.

fn server_data() -> Vec<u8> {
    let mut x: u32 = 42;
    (0..1 << 20)
        .map(|_| {
            x = x.wrapping_mul(1664525).wrapping_add(1013904223);
            (x >> 24) as u8
        })
        .collect()
}

#[test]
fn server_signature_is_consumable_by_the_client() {
    let sig = fast_rsync::Signature::deserialize(
        include_bytes!("fixtures/server_signature.bin").to_vec(),
    )
    .expect("the server signature must parse");

    // stale local copy: the server file with a 4KiB region rewritten
    let server = server_data();
    let mut local = server.clone();
    for b in &mut local[300 * 1024..304 * 1024] {
        *b ^= 0xAA;
    }

    // rolling local over the server blocks must find everything but the edit
    let mut delta = Vec::new();
    fast_rsync::diff(&sig.index(), &local, &mut delta).expect("diff against the server signature");
    assert!(
        delta.len() < 32 * 1024,
        "4KiB edit produced a {} bytes delta, cross-implementation block matching is broken",
        delta.len()
    );

    // and the resulting delta must reconstruct the local file from the server one
    let mut restored = Vec::new();
    fast_rsync::apply(&server, &delta, &mut restored).expect("apply");
    assert_eq!(restored, local);
}
