name: Filestash
options:
  bundleIdPrefix: app.filestash
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  Filestash:
    type: application
    platform: macOS
    sources:
      - App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.filestash.mac
        PRODUCT_NAME: Filestash
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3736F8X9F9
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: Filestash
        LSUIElement: true
